"use client";

import { useCallback, useEffect, useRef, useState } from "react";

const copy = {
  title: "AI Pricing Training", intro: "Submit one completed preview job at a time. Staff approval teaches the model; applying its proposal updates the live quote logic.",
  vehicle: "Vehicle type", vehicleText: "Vehicle details", service: "Service", low: "Approved low", high: "Approved high", notes: "Inspection notes",
  photos: "Job photos", add: "Add training example", adding: "Saving…", approve: "Approve + refine AI", reject: "Reject", pending: "Pending staff review",
  approved: "Approved", rejected: "Rejected", propose: "Re-run AI refinement", apply: "Apply proposal to live pricing", noData: "No training examples yet.",
};

export default function TrainingDashboard({ initialPricing }) {
  const [examples, setExamples] = useState([]); const [form, setForm] = useState({ vehicleClassId: initialPricing.vehicleClasses[0]?.id || "", vehicleText: "", serviceId: initialPricing.services[0]?.id || "", approvedLow: "", approvedHigh: "", inspectionNotes: "" });
  const [files, setFiles] = useState([]); const [proposal, setProposal] = useState(null); const [source, setSource] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const fileRef = useRef(null);
  const load = useCallback(async () => { const res = await fetch("/api/admin/training", { cache: "no-store" }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Could not load training."); setExamples(data.examples || []); }, []);
  useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  const update = (key, value) => setForm((old) => ({ ...old, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); files.forEach((file) => body.append("photos", file)); const res = await fetch("/api/admin/training", { method: "POST", body }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Could not save example."); setFiles([]); event.target.reset(); setForm((old) => ({ ...old, vehicleText: "", approvedLow: "", approvedHigh: "", inspectionNotes: "" })); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const status = async (id, value) => { setBusy(true); setError(""); try { const res = await fetch("/api/admin/training", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "status", id, status: value }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Training update failed."); if (data.proposedPricing) { setProposal(data.proposedPricing); setSource(data.proposalSource || ""); } await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const refine = async () => { setBusy(true); setError(""); try { const res = await fetch("/api/admin/training", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "proposal" }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "AI refinement failed."); setProposal(data.proposedPricing); setSource(data.proposalSource || ""); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const apply = async () => { if (!proposal || !window.confirm("Apply this reviewed AI proposal to live pricing?")) return; setBusy(true); try { const res = await fetch("/api/admin/training", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "apply", pricing: proposal }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Could not apply proposal."); window.location.reload(); } catch (e) { setError(e.message); setBusy(false); } };
  const label = (items, id) => items.find((x) => x.id === id)?.label?.en || id;
  return <div className="training-dash">
    <h2 className="booking-dash__title">{copy.title}</h2><p className="training-dash__intro">{copy.intro}</p>
    {error && <p className="cal__create-error">{error}</p>}
    <form className="training-form" onSubmit={submit}>
      <label>{copy.vehicle}<select value={form.vehicleClassId} onChange={(e) => update("vehicleClassId", e.target.value)}>{initialPricing.vehicleClasses.map((x) => <option key={x.id} value={x.id}>{x.label.en}</option>)}</select></label>
      <label>{copy.service}<select value={form.serviceId} onChange={(e) => update("serviceId", e.target.value)}>{initialPricing.services.map((x) => <option key={x.id} value={x.id}>{x.label.en}</option>)}</select></label>
      <label>{copy.vehicleText}<input value={form.vehicleText} onChange={(e) => update("vehicleText", e.target.value)} placeholder="2018 Toyota Camry" /></label>
      <label>{copy.low}<input required type="number" min="0" step="1" value={form.approvedLow} onChange={(e) => update("approvedLow", e.target.value)} /></label>
      <label>{copy.high}<input required type="number" min="0" step="1" value={form.approvedHigh} onChange={(e) => update("approvedHigh", e.target.value)} /></label>
      <label className="training-form__wide">{copy.notes}<textarea value={form.inspectionNotes} onChange={(e) => update("inspectionNotes", e.target.value)} /></label>
      <div className="training-upload training-form__wide" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); setFiles(Array.from(e.dataTransfer.files).filter((x) => x.type.startsWith("image/"))); }} onClick={() => fileRef.current?.click()}><input ref={fileRef} type="file" accept="image/*" multiple hidden onChange={(e) => setFiles(Array.from(e.target.files || []))} /><strong>{copy.photos}</strong><span>{files.length ? `${files.length} selected` : "Click or drag photos here"}</span></div>
      <button className="btn btn--primary training-form__wide" type="submit" disabled={busy}>{busy ? copy.adding : copy.add}</button>
    </form>
    <div className="training-dash__toolbar"><h3>Examples ({examples.length})</h3><button className="btn btn--ghost btn--small" onClick={refine} disabled={busy}>{copy.propose}</button></div>
    {!examples.length && <p className="cal__empty">{copy.noData}</p>}
    <div className="training-list">{examples.map((item) => <article className="training-card" key={item.id}><div><strong>{label(initialPricing.services, item.serviceId)}</strong><span>{label(initialPricing.vehicleClasses, item.vehicleClassId)} · ${item.approvedLow}–${item.approvedHigh}</span><small>{item.vehicleText || "Vehicle details not entered"}</small>{item.inspectionNotes && <small>{item.inspectionNotes}</small>}</div><div className="training-card__photos">{item.photos.map((url, i) => <img key={i} src={url} alt="Training job" />)}</div><div className="training-card__actions"><span className={`training-status training-status--${item.status}`}>{item.status === "pending" ? copy.pending : item.status === "approved" ? copy.approved : copy.rejected}</span>{item.status === "pending" && <><button className="btn btn--primary btn--small" onClick={() => status(item.id, "approved")} disabled={busy}>{copy.approve}</button><button className="btn btn--ghost btn--small" onClick={() => status(item.id, "rejected")} disabled={busy}>{copy.reject}</button></>}</div></article>)}</div>
    {proposal && <section className="training-proposal"><h3>AI proposal ready for review</h3><p>Source: {source || "AI refinement"}. It uses every approved example and the attached job photos. Apply only after staff review.</p><div className="training-proposal__summary">{proposal.services.map((service) => { const before = initialPricing.services.find((x) => x.id === service.id); const field = service.model === "labor" ? "partsBase" : service.model === "flat" ? "flatPrice" : service.model === "perUnit" ? "basePrice" : "options"; const oldValue = field === "options" ? before?.options?.map((x) => x.price).join(", ") : before?.[field]; const newValue = field === "options" ? service.options?.map((x) => x.price).join(", ") : service[field]; return oldValue !== newValue ? <span key={service.id}>{service.label.en}: {oldValue} → {newValue}</span> : null; })}</div><button className="btn btn--primary" onClick={apply} disabled={busy}>{copy.apply}</button><button className="btn btn--ghost" onClick={() => setProposal(null)}>Discard</button></section>}
  </div>;
}
