// Vehicle makes + models for the quote estimator.
// Model IDs are sanitised (lowercase, no spaces, no special chars) and double
// as the filename segment for vehicle photos in public/vehicles/:
//   {makeId}{modelId}{year}.png   e.g.  toyotacamry2020.png

const START_YEAR = 2000;

export const VEHICLE_YEARS = Array.from(
  { length: new Date().getFullYear() + 2 - START_YEAR },
  (_, i) => START_YEAR + i,
);

// Helper so image filenames are consistent everywhere.
// Tries .png first, then .webp so users can drop either format.
const IMG_EXTS = ["png", "webp", "jpg", "jpeg"];
export function vehicleImagePath(makeId, modelId, year, ext = "png") {
  return `/vehicles/${makeId}${modelId}${year}.${ext}`;
}
export function vehicleImageExts() {
  return IMG_EXTS;
}

export const MAKES = [
  {
    id: "acura",
    name: { en: "Acura", es: "Acura" },
    classId: "luxury_perf",
    models: [
      { id: "cl", label: { en: "CL", es: "CL" } },
      { id: "eldorado", label: { en: "Eldorado", es: "Eldorado" } },
      { id: "ilx", label: { en: "ILX", es: "ILX" } },
      { id: "integra", label: { en: "Integra", es: "Integra" } },
      { id: "legend", label: { en: "Legend", es: "Legend" } },
      { id: "mdx", label: { en: "MDX", es: "MDX" } },
      { id: "nsx", label: { en: "NSX", es: "NSX" } },
      { id: "rdx", label: { en: "RDX", es: "RDX" } },
      { id: "rl", label: { en: "RL", es: "RL" } },
      { id: "rlx", label: { en: "RLX", es: "RLX" } },
      { id: "rsx", label: { en: "RSX", es: "RSX" } },
      { id: "slx", label: { en: "SLX", es: "SLX" } },
      { id: "tl", label: { en: "TL", es: "TL" } },
      { id: "tlx", label: { en: "TLX", es: "TLX" } },
      { id: "tsx", label: { en: "TSX", es: "TSX" } },
      { id: "vigor", label: { en: "Vigor", es: "Vigor" } },
      { id: "zdx", label: { en: "ZDX", es: "ZDX" } },
    ],
  },
  {
    id: "alfaromeo",
    name: { en: "Alfa Romeo", es: "Alfa Romeo" },
    classId: "luxury_perf",
    models: [
      { id: "4c", label: { en: "4C", es: "4C" } },
      { id: "giulia", label: { en: "Giulia", es: "Giulia" } },
      { id: "stelvio", label: { en: "Stelvio", es: "Stelvio" } },
      { id: "tonale", label: { en: "Tonale", es: "Tonale" } },
    ],
  },
  {
    id: "astonmartin",
    name: { en: "Aston Martin", es: "Aston Martin" },
    classId: "luxury_perf",
    models: [
      { id: "db11", label: { en: "DB11", es: "DB11" } },
      { id: "db12", label: { en: "DB12", es: "DB12" } },
      { id: "db9", label: { en: "DB9", es: "DB9" } },
      { id: "dbs", label: { en: "DBS", es: "DBS" } },
      { id: "dbx", label: { en: "DBX", es: "DBX" } },
      { id: "rapide", label: { en: "Rapide", es: "Rapide" } },
      { id: "vantage", label: { en: "Vantage", es: "Vantage" } },
    ],
  },
  {
    id: "audi",
    name: { en: "Audi", es: "Audi" },
    classId: "luxury_perf",
    models: [
      { id: "a3", label: { en: "A3", es: "A3" } },
      { id: "a4", label: { en: "A4", es: "A4" } },
      { id: "a5", label: { en: "A5", es: "A5" } },
      { id: "a6", label: { en: "A6", es: "A6" } },
      { id: "a7", label: { en: "A7", es: "A7" } },
      { id: "a8", label: { en: "A8", es: "A8" } },
      { id: "allroad", label: { en: "Allroad", es: "Allroad" } },
      { id: "etron", label: { en: "e-tron", es: "e-tron" } },
      { id: "q3", label: { en: "Q3", es: "Q3" } },
      { id: "q5", label: { en: "Q5", es: "Q5" } },
      { id: "q7", label: { en: "Q7", es: "Q7" } },
      { id: "q8", label: { en: "Q8", es: "Q8" } },
      { id: "q4etron", label: { en: "Q4 e-tron", es: "Q4 e-tron" } },
      { id: "r8", label: { en: "R8", es: "R8" } },
      { id: "rs3", label: { en: "RS3", es: "RS3" } },
      { id: "rs5", label: { en: "RS5", es: "RS5" } },
      { id: "rs6", label: { en: "RS6", es: "RS6" } },
      { id: "s3", label: { en: "S3", es: "S3" } },
      { id: "s4", label: { en: "S4", es: "S4" } },
      { id: "s5", label: { en: "S5", es: "S5" } },
      { id: "sq5", label: { en: "SQ5", es: "SQ5" } },
      { id: "tt", label: { en: "TT", es: "TT" } },
    ],
  },
  {
    id: "bentley",
    name: { en: "Bentley", es: "Bentley" },
    classId: "luxury_perf",
    models: [
      { id: "bentayga", label: { en: "Bentayga", es: "Bentayga" } },
      { id: "continental", label: { en: "Continental GT", es: "Continental GT" } },
      { id: "flying", label: { en: "Flying Spur", es: "Flying Spur" } },
      { id: "mulsanne", label: { en: "Mulsanne", es: "Mulsanne" } },
    ],
  },
  {
    id: "bmw",
    name: { en: "BMW", es: "BMW" },
    classId: "luxury_perf",
    models: [
      { id: "2series", label: { en: "2 Series", es: "Serie 2" } },
      { id: "3series", label: { en: "3 Series", es: "Serie 3" } },
      { id: "4series", label: { en: "4 Series", es: "Serie 4" } },
      { id: "5series", label: { en: "5 Series", es: "Serie 5" } },
      { id: "6series", label: { en: "6 Series", es: "Serie 6" } },
      { id: "7series", label: { en: "7 Series", es: "Serie 7" } },
      { id: "8series", label: { en: "8 Series", es: "Serie 8" } },
      { id: "i3", label: { en: "i3", es: "i3" } },
      { id: "i4", label: { en: "i4", es: "i4" } },
      { id: "i5", label: { en: "i5", es: "i5" } },
      { id: "i7", label: { en: "i7", es: "i7" } },
      { id: "ix", label: { en: "iX", es: "iX" } },
      { id: "ix3", label: { en: "iX3", es: "iX3" } },
      { id: "m2", label: { en: "M2", es: "M2" } },
      { id: "m3", label: { en: "M3", es: "M3" } },
      { id: "m4", label: { en: "M4", es: "M4" } },
      { id: "m5", label: { en: "M5", es: "M5" } },
      { id: "m6", label: { en: "M6", es: "M6" } },
      { id: "m8", label: { en: "M8", es: "M8" } },
      { id: "x1", label: { en: "X1", es: "X1" } },
      { id: "x2", label: { en: "X2", es: "X2" } },
      { id: "x3", label: { en: "X3", es: "X3" } },
      { id: "x3m", label: { en: "X3 M", es: "X3 M" } },
      { id: "x4", label: { en: "X4", es: "X4" } },
      { id: "x4m", label: { en: "X4 M", es: "X4 M" } },
      { id: "x5", label: { en: "X5", es: "X5" } },
      { id: "x5m", label: { en: "X5 M", es: "X5 M" } },
      { id: "x6", label: { en: "X6", es: "X6" } },
      { id: "x6m", label: { en: "X6 M", es: "X6 M" } },
      { id: "x7", label: { en: "X7", es: "X7" } },
      { id: "xm", label: { en: "XM", es: "XM" } },
      { id: "z3", label: { en: "Z3", es: "Z3" } },
      { id: "z4", label: { en: "Z4", es: "Z4" } },
    ],
  },
  {
    id: "buick",
    name: { en: "Buick", es: "Buick" },
    classId: "sedan",
    models: [
      { id: "encore", label: { en: "Encore", es: "Encore" } },
      { id: "encoregx", label: { en: "Encore GX", es: "Encore GX" } },
      { id: "enclave", label: { en: "Enclave", es: "Enclave" } },
      { id: "envista", label: { en: "Envista", es: "Envista" } },
      { id: "lacrosse", label: { en: "LaCrosse", es: "LaCrosse" } },
      { id: "lucerne", label: { en: "Lucerne", es: "Lucerne" } },
      { id: "regal", label: { en: "Regal", es: "Regal" } },
      { id: "rendezvous", label: { en: "Rendezvous", es: "Rendezvous" } },
    ],
  },
  {
    id: "cadillac",
    name: { en: "Cadillac", es: "Cadillac" },
    classId: "luxury_perf",
    models: [
      { id: "ats", label: { en: "ATS", es: "ATS" } },
      { id: "celestiq", label: { en: "Celestiq", es: "Celestiq" } },
      { id: "cts", label: { en: "CTS", es: "CTS" } },
      { id: "dts", label: { en: "DTS", es: "DTS" } },
      { id: "eldorado", label: { en: "Eldorado", es: "Eldorado" } },
      { id: "escalade", label: { en: "Escalade", es: "Escalade" } },
      { id: "escaladev", label: { en: "Escalade-V", es: "Escalade-V" } },
      { id: "lyriq", label: { en: "LYRIQ", es: "LYRIQ" } },
      { id: "seville", label: { en: "Seville", es: "Seville" } },
      { id: "srx", label: { en: "SRX", es: "SRX" } },
      { id: "sts", label: { en: "STS", es: "STS" } },
      { id: "xt4", label: { en: "XT4", es: "XT4" } },
      { id: "xt5", label: { en: "XT5", es: "XT5" } },
      { id: "xt6", label: { en: "XT6", es: "XT6" } },
      { id: "xjr", label: { en: "XJR", es: "XJR" } },
    ],
  },
  {
    id: "chevrolet",
    name: { en: "Chevrolet", es: "Chevrolet" },
    classId: "sedan",
    models: [
      { id: "aveo", label: { en: "Aveo", es: "Aveo" } },
      { id: "blazer", label: { en: "Blazer", es: "Blazer" } },
      { id: "boltev", label: { en: "Bolt EV", es: "Bolt EV" } },
      { id: "bolteuv", label: { en: "Bolt EUV", es: "Bolt EUV" } },
      { id: "camaro", label: { en: "Camaro", es: "Camaro" } },
      { id: "caprice", label: { en: "Caprice", es: "Caprice" } },
      { id: "captiva", label: { en: "Captiva", es: "Captiva" } },
      { id: "cobalt", label: { en: "Cobalt", es: "Cobalt" } },
      { id: "colorado", label: { en: "Colorado", es: "Colorado" } },
      { id: "corvette", label: { en: "Corvette", es: "Corvette" } },
      { id: "cruze", label: { en: "Cruze", es: "Cruze" } },
      { id: "equinox", label: { en: "Equinox", es: "Equinox" } },
      { id: "express", label: { en: "Express", es: "Express" } },
      { id: "hhr", label: { en: "HHR", es: "HHR" } },
      { id: "impala", label: { en: "Impala", es: "Impala" } },
      { id: "lt", label: { en: "LUV", es: "LUV" } },
      { id: "malibu", label: { en: "Malibu", es: "Malibu" } },
      { id: "monte", label: { en: "Monte Carlo", es: "Monte Carlo" } },
      { id: "silverado1500", label: { en: "Silverado 1500", es: "Silverado 1500" } },
      { id: "silverado2500hd", label: { en: "Silverado 2500HD", es: "Silverado 2500HD" } },
      { id: "silverado3500hd", label: { en: "Silverado 3500HD", es: "Silverado 3500HD" } },
      { id: "spark", label: { en: "Spark", es: "Spark" } },
      { id: "ss", label: { en: "SS", es: "SS" } },
      { id: "suburban", label: { en: "Suburban", es: "Suburban" } },
      { id: "tahoe", label: { en: "Tahoe", es: "Tahoe" } },
      { id: "trailblazer", label: { en: "TrailBlazer", es: "TrailBlazer" } },
      { id: "traverse", label: { en: "Traverse", es: "Traverse" } },
      { id: "trax", label: { en: "Trax", es: "Trax" } },
      { id: "uplaander", label: { en: "Uplander", es: "Uplander" } },
      { id: "volt", label: { en: "Volt", es: "Volt" } },
    ],
  },
  {
    id: "chrysler",
    name: { en: "Chrysler", es: "Chrysler" },
    classId: "sedan",
    models: [
      { id: "200", label: { en: "200", es: "200" } },
      { id: "300", label: { en: "300", es: "300" } },
      { id: "aspen", label: { en: "Aspen", es: "Aspen" } },
      { id: "crossfire", label: { en: "Crossfire", es: "Crossfire" } },
      { id: "grandvoyager", label: { en: "Grand Voyager", es: "Grand Voyager" } },
      { id: "pacific", label: { en: "Pacific", es: "Pacific" } },
      { id: "ptcruiser", label: { en: "PT Cruiser", es: "PT Cruiser" } },
      { id: "sebring", label: { en: "Sebring", es: "Sebring" } },
      { id: "towncountry", label: { en: "Town & Country", es: "Town & Country" } },
      { id: "voyager", label: { en: "Voyager", es: "Voyager" } },
    ],
  },
  {
    id: "dodge",
    name: { en: "Dodge", es: "Dodge" },
    classId: "sedan",
    models: [
      { id: "avenger", label: { en: "Avenger", es: "Avenger" } },
      { id: "caliber", label: { en: "Caliber", es: "Caliber" } },
      { id: "caravan", label: { en: "Grand Caravan", es: "Grand Caravan" } },
      { id: "challenger", label: { en: "Challenger", es: "Challenger" } },
      { id: "charger", label: { en: "Charger", es: "Charger" } },
      { id: "dakota", label: { en: "Dakota", es: "Dakota" } },
      { id: "dart", label: { en: "Dart", es: "Dart" } },
      { id: "durango", label: { en: "Durango", es: "Durango" } },
      { id: "hornet", label: { en: "Hornet", es: "Hornet" } },
      { id: "intrepid", label: { en: "Intrepid", es: "Intrepid" } },
      { id: "journey", label: { en: "Journey", es: "Journey" } },
      { id: "magnum", label: { en: "Magnum", es: "Magnum" } },
      { id: "neon", label: { en: "Neon", es: "Neon" } },
      { id: "nitro", label: { en: "Nitro", es: "Nitro" } },
      { id: "ram1500", label: { en: "Ram 1500 (old)", es: "Ram 1500 (viejo)" } },
      { id: "ram2500", label: { en: "Ram 2500 (old)", es: "Ram 2500 (viejo)" } },
      { id: "viper", label: { en: "Viper", es: "Viper" } },
    ],
  },
  {
    id: "ferrari",
    name: { en: "Ferrari", es: "Ferrari" },
    classId: "luxury_perf",
    models: [
      { id: "296gtb", label: { en: "296 GTB", es: "296 GTB" } },
      { id: "458", label: { en: "458 Italia", es: "458 Italia" } },
      { id: "488", label: { en: "488 GTB", es: "488 GTB" } },
      { id: "812", label: { en: "812 Superfast", es: "812 Superfast" } },
      { id: "california", label: { en: "California", es: "California" } },
      { id: "f430", label: { en: "F430", es: "F430" } },
      { id: "ff", label: { en: "FF", es: "FF" } },
      { id: "gct4", label: { en: "GTC4Lusso", es: "GTC4Lusso" } },
      { id: "portofino", label: { en: "Portofino", es: "Portofino" } },
      { id: "roma", label: { en: "Roma", es: "Roma" } },
      { id: "sf90", label: { en: "SF90 Stradale", es: "SF90 Stradale" } },
      { id: "puro", label: { en: "Purosangue", es: "Purosangue" } },
    ],
  },
  {
    id: "fiat",
    name: { en: "Fiat", es: "Fiat" },
    classId: "compact",
    models: [
      { id: "124spider", label: { en: "124 Spider", es: "124 Spider" } },
      { id: "500", label: { en: "500", es: "500" } },
      { id: "500c", label: { en: "500c", es: "500c" } },
      { id: "500l", label: { en: "500L", es: "500L" } },
      { id: "500x", label: { en: "500X", es: "500X" } },
    ],
  },
  {
    id: "ford",
    name: { en: "Ford", es: "Ford" },
    classId: "sedan",
    models: [
      { id: "bronco", label: { en: "Bronco", es: "Bronco" } },
      { id: "broncosport", label: { en: "Bronco Sport", es: "Bronco Sport" } },
      { id: "cmaxt", label: { en: "C-MAX", es: "C-MAX" } },
      { id: "ecosport", label: { en: "EcoSport", es: "EcoSport" } },
      { id: "edge", label: { en: "Edge", es: "Edge" } },
      { id: "escape", label: { en: "Escape", es: "Escape" } },
      { id: "expedition", label: { en: "Expedition", es: "Expedition" } },
      { id: "explorer", label: { en: "Explorer", es: "Explorer" } },
      { id: "f150", label: { en: "F-150", es: "F-150" } },
      { id: "f250", label: { en: "F-250 Super Duty", es: "F-250 Super Duty" } },
      { id: "f350", label: { en: "F-350 Super Duty", es: "F-350 Super Duty" } },
      { id: "f450", label: { en: "F-450 Super Duty", es: "F-450 Super Duty" } },
      { id: "fiesta", label: { en: "Fiesta", es: "Fiesta" } },
      { id: "flex", label: { en: "Flex", es: "Flex" } },
      { id: "focus", label: { en: "Focus", es: "Focus" } },
      { id: "fusion", label: { en: "Fusion", es: "Fusion" } },
      { id: "mustang", label: { en: "Mustang", es: "Mustang" } },
      { id: "mustangmache", label: { en: "Mustang Mach-E", es: "Mustang Mach-E" } },
      { id: "ranger", label: { en: "Ranger", es: "Ranger" } },
      { id: "taurus", label: { en: "Taurus", es: "Taurus" } },
      { id: "thunderbird", label: { en: "Thunderbird", es: "Thunderbird" } },
      { id: "transit", label: { en: "Transit", es: "Transit" } },
      { id: "transitconnect", label: { en: "Transit Connect", es: "Transit Connect" } },
    ],
  },
  {
    id: "genesis",
    name: { en: "Genesis", es: "Genesis" },
    classId: "luxury_perf",
    models: [
      { id: "g70", label: { en: "G70", es: "G70" } },
      { id: "g80", label: { en: "G80", es: "G80" } },
      { id: "g90", label: { en: "G90", es: "G90" } },
      { id: "gv60", label: { en: "GV60", es: "GV60" } },
      { id: "gv70", label: { en: "GV70", es: "GV70" } },
      { id: "gv80", label: { en: "GV80", es: "GV80" } },
    ],
  },
  {
    id: "gmc",
    name: { en: "GMC", es: "GMC" },
    classId: "suv_truck",
    models: [
      { id: "acadia", label: { en: "Acadia", es: "Acadia" } },
      { id: "canyon", label: { en: "Canyon", es: "Canyon" } },
      { id: "envoy", label: { en: "Envoy", es: "Envoy" } },
      { id: "hummercanyonev", label: { en: "Hummer EV SUV", es: "Hummer EV SUV" } },
      { id: "hummerpickup", label: { en: "Hummer EV Pickup", es: "Hummer EV Pickup" } },
      { id: "safari", label: { en: "Safari", es: "Safari" } },
      { id: "savana", label: { en: "Savana", es: "Savana" } },
      { id: "sierra1500", label: { en: "Sierra 1500", es: "Sierra 1500" } },
      { id: "sierra2500hd", label: { en: "Sierra 2500HD", es: "Sierra 2500HD" } },
      { id: "sierra3500hd", label: { en: "Sierra 3500HD", es: "Sierra 3500HD" } },
      { id: "terrain", label: { en: "Terrain", es: "Terrain" } },
      { id: "yukon", label: { en: "Yukon", es: "Yukon" } },
      { id: "yukonxl", label: { en: "Yukon XL", es: "Yukon XL" } },
    ],
  },
  {
    id: "honda",
    name: { en: "Honda", es: "Honda" },
    classId: "sedan",
    models: [
      { id: "accord", label: { en: "Accord", es: "Accord" } },
      { id: "civic", label: { en: "Civic", es: "Civic" } },
      { id: "clarity", label: { en: "Clarity", es: "Clarity" } },
      { id: "crv", label: { en: "CR-V", es: "CR-V" } },
      { id: "crz", label: { en: "CR-Z", es: "CR-Z" } },
      { id: "element", label: { en: "Element", es: "Element" } },
      { id: "fit", label: { en: "Fit", es: "Fit" } },
      { id: "hrv", label: { en: "HR-V", es: "HR-V" } },
      { id: "insight", label: { en: "Insight", es: "Insight" } },
      { id: "odyssey", label: { en: "Odyssey", es: "Odyssey" } },
      { id: "passport", label: { en: "Passport", es: "Passport" } },
      { id: "pilot", label: { en: "Pilot", es: "Pilot" } },
      { id: "prologue", label: { en: "Prologue", es: "Prologue" } },
      { id: "ridgeline", label: { en: "Ridgeline", es: "Ridgeline" } },
      { id: "s2000", label: { en: "S2000", es: "S2000" } },
    ],
  },
  {
    id: "hummer",
    name: { en: "Hummer", es: "Hummer" },
    classId: "suv_truck",
    models: [
      { id: "h2", label: { en: "H2", es: "H2" } },
      { id: "h3", label: { en: "H3", es: "H3" } },
    ],
  },
  {
    id: "hyundai",
    name: { en: "Hyundai", es: "Hyundai" },
    classId: "sedan",
    models: [
      { id: "accents", label: { en: "Accent", es: "Accent" } },
      { id: "azera", label: { en: "Azera", es: "Azera" } },
      { id: "elantra", label: { en: "Elantra", es: "Elantra" } },
      { id: "elantragt", label: { en: "Elantra GT", es: "Elantra GT" } },
      { id: "equus", label: { en: "Equus", es: "Equus" } },
      { id: "genesis", label: { en: "Genesis", es: "Genesis" } },
      { id: "getz", label: { en: "Getz", es: "Getz" } },
      { id: "i10", label: { en: "i10", es: "i10" } },
      { id: "ioniq5", label: { en: "IONIQ 5", es: "IONIQ 5" } },
      { id: "ioniq6", label: { en: "IONIQ 6", es: "IONIQ 6" } },
      { id: "kona", label: { en: "Kona", es: "Kona" } },
      { id: "nexo", label: { en: "Nexo", es: "Nexo" } },
      { id: "palissade", label: { en: "Palisade", es: "Palisade" } },
      { id: "santafe", label: { en: "Santa Fe", es: "Santa Fe" } },
      { id: "sonata", label: { en: "Sonata", es: "Sonata" } },
      { id: "tucson", label: { en: "Tucson", es: "Tucson" } },
      { id: "veloster", label: { en: "Veloster", es: "Veloster" } },
      { id: "venue", label: { en: "Venue", es: "Venue" } },
    ],
  },
  {
    id: "infiniti",
    name: { en: "Infiniti", es: "Infiniti" },
    classId: "luxury_perf",
    models: [
      { id: "ex35", label: { en: "EX35", es: "EX35" } },
      { id: "fx35", label: { en: "FX35", es: "FX35" } },
      { id: "fx45", label: { en: "FX45", es: "FX45" } },
      { id: "g20", label: { en: "G20", es: "G20" } },
      { id: "g25", label: { en: "G25", es: "G25" } },
      { id: "g35", label: { en: "G35", es: "G35" } },
      { id: "g37", label: { en: "G37", es: "G37" } },
      { id: "i30", label: { en: "I30", es: "I30" } },
      { id: "i35", label: { en: "I35", es: "I35" } },
      { id: "j30", label: { en: "J30", es: "J30" } },
      { id: "jx35", label: { en: "JX35", es: "JX35" } },
      { id: "m35", label: { en: "M35", es: "M35" } },
      { id: "m37", label: { en: "M37", es: "M37" } },
      { id: "q30", label: { en: "Q30", es: "Q30" } },
      { id: "q40", label: { en: "Q40", es: "Q40" } },
      { id: "q50", label: { en: "Q50", es: "Q50" } },
      { id: "q60", label: { en: "Q60", es: "Q60" } },
      { id: "q70", label: { en: "Q70", es: "Q70" } },
      { id: "qx30", label: { en: "QX30", es: "QX30" } },
      { id: "qx4", label: { en: "QX4", es: "QX4" } },
      { id: "qx50", label: { en: "QX50", es: "QX50" } },
      { id: "qx55", label: { en: "QX55", es: "QX55" } },
      { id: "qx56", label: { en: "QX56", es: "QX56" } },
      { id: "qx60", label: { en: "QX60", es: "QX60" } },
      { id: "qx70", label: { en: "QX70", es: "QX70" } },
      { id: "qx80", label: { en: "QX80", es: "QX80" } },
    ],
  },
  {
    id: "jaguar",
    name: { en: "Jaguar", es: "Jaguar" },
    classId: "luxury_perf",
    models: [
      { id: "epace", label: { en: "E-Pace", es: "E-Pace" } },
      { id: "fpace", label: { en: "F-Pace", es: "F-Pace" } },
      { id: "ftype", label: { en: "F-Type", es: "F-Type" } },
      { id: "ipace", label: { en: "I-Pace", es: "I-Pace" } },
      { id: "s_type", label: { en: "S-Type", es: "S-Type" } },
      { id: "xf", label: { en: "XF", es: "XF" } },
      { id: "xj", label: { en: "XJ", es: "XJ" } },
      { id: "xj8", label: { en: "XJ8", es: "XJ8" } },
      { id: "xjs", label: { en: "XJS", es: "XJS" } },
      { id: "xk", label: { en: "XK", es: "XK" } },
      { id: "xkr", label: { en: "XKR", es: "XKR" } },
      { id: "xe", label: { en: "XE", es: "XE" } },
    ],
  },
  {
    id: "jeep",
    name: { en: "Jeep", es: "Jeep" },
    classId: "suv_truck",
    models: [
      { id: "cherokee", label: { en: "Cherokee", es: "Cherokee" } },
      { id: "cj5", label: { en: "CJ-5", es: "CJ-5" } },
      { id: "comanche", label: { en: "Comanche", es: "Comanche" } },
      { id: "commander", label: { en: "Commander", es: "Commander" } },
      { id: "compass", label: { en: "Compass", es: "Compass" } },
      { id: "gladiator", label: { en: "Gladiator", es: "Gladiator" } },
      { id: "grandcherokee", label: { en: "Grand Cherokee", es: "Grand Cherokee" } },
      { id: "liberty", label: { en: "Liberty", es: "Liberty" } },
      { id: "patriot", label: { en: "Patriot", es: "Patriot" } },
      { id: "renegade", label: { en: "Renegade", es: "Renegade" } },
      { id: "wagoneer", label: { en: "Wagoneer", es: "Wagoneer" } },
      { id: "wrangler", label: { en: "Wrangler", es: "Wrangler" } },
    ],
  },
  {
    id: "kia",
    name: { en: "Kia", es: "Kia" },
    classId: "sedan",
    models: [
      { id: "amanti", label: { en: "Amanti", es: "Amanti" } },
      { id: "borrego", label: { en: "Borrego", es: "Borrego" } },
      { id: "cadenza", label: { en: "Cadenza", es: "Cadenza" } },
      { id: "carnival", label: { en: "Carnival", es: "Carnival" } },
      { id: "ev6", label: { en: "EV6", es: "EV6" } },
      { id: "ev9", label: { en: "EV9", es: "EV9" } },
      { id: "forte", label: { en: "Forte", es: "Forte" } },
      { id: "k5", label: { en: "K5", es: "K5" } },
      { id: "niro", label: { en: "Niro", es: "Niro" } },
      { id: "optima", label: { en: "Optima", es: "Optima" } },
      { id: "rio", label: { en: "Rio", es: "Rio" } },
      { id: "sedona", label: { en: "Sedona", es: "Sedona" } },
      { id: "selltos", label: { en: "Seltos", es: "Seltos" } },
      { id: "sorento", label: { en: "Sorento", es: "Sorento" } },
      { id: "soul", label: { en: "Soul", es: "Soul" } },
      { id: "spectra", label: { en: "Spectra", es: "Spectra" } },
      { id: "sportage", label: { en: "Sportage", es: "Sportage" } },
      { id: "stinger", label: { en: "Stinger", es: "Stinger" } },
      { id: "telluride", label: { en: "Telluride", es: "Telluride" } },
    ],
  },
  {
    id: "lamborghini",
    name: { en: "Lamborghini", es: "Lamborghini" },
    classId: "luxury_perf",
    models: [
      { id: "aventador", label: { en: "Aventador", es: "Aventador" } },
      { id: "countach", label: { en: "Countach", es: "Countach" } },
      { id: "diablo", label: { en: "Diablo", es: "Diablo" } },
      { id: "gallardo", label: { en: "Gallardo", es: "Gallardo" } },
      { id: "huracan", label: { en: "Huracán", es: "Huracán" } },
      { id: "murcielago", label: { en: "Murciélago", es: "Murciélago" } },
      { id: "revuelto", label: { en: "Revuelto", es: "Revuelto" } },
      { id: "urus", label: { en: "Urus", es: "Urus" } },
    ],
  },
  {
    id: "landrover",
    name: { en: "Land Rover", es: "Land Rover" },
    classId: "luxury_perf",
    models: [
      { id: "defender", label: { en: "Defender", es: "Defender" } },
      { id: "discovery", label: { en: "Discovery", es: "Discovery" } },
      { id: "discoverysport", label: { en: "Discovery Sport", es: "Discovery Sport" } },
      { id: "evoque", label: { en: "Evoque", es: "Evoque" } },
      { id: "freelander", label: { en: "Freelander", es: "Freelander" } },
      { id: "range", label: { en: "Range Rover", es: "Range Rover" } },
      { id: "rangeevoque", label: { en: "Range Rover Evoque", es: "Range Rover Evoque" } },
      { id: "rangesport", label: { en: "Range Rover Sport", es: "Range Rover Sport" } },
      { id: "rangevelar", label: { en: "Range Rover Velar", es: "Range Rover Velar" } },
    ],
  },
  {
    id: "lexus",
    name: { en: "Lexus", es: "Lexus" },
    classId: "luxury_perf",
    models: [
      { id: "es250", label: { en: "ES 250", es: "ES 250" } },
      { id: "es300", label: { en: "ES 300", es: "ES 300" } },
      { id: "es330", label: { en: "ES 330", es: "ES 330" } },
      { id: "es350", label: { en: "ES 350", es: "ES 350" } },
      { id: "gs300", label: { en: "GS 300", es: "GS 300" } },
      { id: "gs350", label: { en: "GS 350", es: "GS 350" } },
      { id: "gs430", label: { en: "GS 430", es: "GS 430" } },
      { id: "gx460", label: { en: "GX 460", es: "GX 460" } },
      { id: "gx470", label: { en: "GX 470", es: "GX 470" } },
      { id: "hs250h", label: { en: "HS 250h", es: "HS 250h" } },
      { id: "is250", label: { en: "IS 250", es: "IS 250" } },
      { id: "is300", label: { en: "IS 300", es: "IS 300" } },
      { id: "is350", label: { en: "IS 350", es: "IS 350" } },
      { id: "lc500", label: { en: "LC 500", es: "LC 500" } },
      { id: "lfa", label: { en: "LFA", es: "LFA" } },
      { id: "ls400", label: { en: "LS 400", es: "LS 400" } },
      { id: "ls430", label: { en: "LS 430", es: "LS 430" } },
      { id: "ls460", label: { en: "LS 460", es: "LS 460" } },
      { id: "ls500", label: { en: "LS 500", es: "LS 500" } },
      { id: "lx470", label: { en: "LX 470", es: "LX 470" } },
      { id: "lx570", label: { en: "LX 570", es: "LX 570" } },
      { id: "lx600", label: { en: "LX 600", es: "LX 600" } },
      { id: "nx200t", label: { en: "NX 200t", es: "NX 200t" } },
      { id: "nx300h", label: { en: "NX 300h", es: "NX 300h" } },
      { id: "nx350h", label: { en: "NX 350h", es: "NX 350h" } },
      { id: "nx450h", label: { en: "NX 450h+", es: "NX 450h+" } },
      { id: "rc350", label: { en: "RC 350", es: "RC 350" } },
      { id: "rcf", label: { en: "RC F", es: "RC F" } },
      { id: "rx330", label: { en: "RX 330", es: "RX 330" } },
      { id: "rx350", label: { en: "RX 350", es: "RX 350" } },
      { id: "rx400h", label: { en: "RX 400h", es: "RX 400h" } },
      { id: "rx450h", label: { en: "RX 450h", es: "RX 450h" } },
      { id: "rx500", label: { en: "RX 500h", es: "RX 500h" } },
      { id: "rz450e", label: { en: "RZ 450e", es: "RZ 450e" } },
      { id: "sc430", label: { en: "SC 430", es: "SC 430" } },
      { id: "tx350", label: { en: "TX 350", es: "TX 350" } },
      { id: "ux200", label: { en: "UX 200", es: "UX 200" } },
      { id: "ux250h", label: { en: "UX 250h", es: "UX 250h" } },
    ],
  },
  {
    id: "lincoln",
    name: { en: "Lincoln", es: "Lincoln" },
    classId: "luxury_perf",
    models: [
      { id: "aviator", label: { en: "Aviator", es: "Aviator" } },
      { id: "blackwood", label: { en: "Blackwood", es: "Blackwood" } },
      { id: "continental", label: { en: "Continental", es: "Continental" } },
      { id: "corsair", label: { en: "Corsair", es: "Corsair" } },
      { id: "ls", label: { en: "LS", es: "LS" } },
      { id: "mkc", label: { en: "MKC", es: "MKC" } },
      { id: "mkd", label: { en: "MKS", es: "MKS" } },
      { id: "mkt", label: { en: "MKT", es: "MKT" } },
      { id: "mkx", label: { en: "MKX", es: "MKX" } },
      { id: "mkz", label: { en: "MKZ", es: "MKZ" } },
      { id: "navigator", label: { en: "Navigator", es: "Navigator" } },
      { id: "navigatorl", label: { en: "Navigator L", es: "Navigator L" } },
      { id: "ntilus", label: { en: "Nautilus", es: "Nautilus" } },
      { id: "towncar", label: { en: "Town Car", es: "Town Car" } },
      { id: "zephyr", label: { en: "Zephyr", es: "Zephyr" } },
    ],
  },
  {
    id: "lotus",
    name: { en: "Lotus", es: "Lotus" },
    classId: "luxury_perf",
    models: [
      { id: "eletre", label: { en: "Eletre", es: "Eletre" } },
      { id: "elis", label: { en: "Elise", es: "Elise" } },
      { id: "emira", label: { en: "Emira", es: "Emira" } },
      { id: "esprit", label: { en: "Esprit", es: "Esprit" } },
      { id: "evija", label: { en: "Evija", es: "Evija" } },
      { id: "exige", label: { en: "Exige", es: "Exige" } },
    ],
  },
  {
    id: "lucid",
    name: { en: "Lucid", es: "Lucid" },
    classId: "luxury_perf",
    models: [
      { id: "air", label: { en: "Air", es: "Air" } },
      { id: "gravity", label: { en: "Gravity", es: "Gravity" } },
    ],
  },
  {
    id: "maserati",
    name: { en: "Maserati", es: "Maserati" },
    classId: "luxury_perf",
    models: [
      { id: "ghibli", label: { en: "Ghibli", es: "Ghibli" } },
      { id: "grancabrio", label: { en: "GranCabrio", es: "GranCabrio" } },
      { id: "granturismo", label: { en: "GranTurismo", es: "GranTurismo" } },
      { id: "grecale", label: { en: "Grecale", es: "Grecale" } },
      { id: "levante", label: { en: "Levante", es: "Levante" } },
      { id: "mc20", label: { en: "MC20", es: "MC20" } },
      { id: "quattroporte", label: { en: "Quattroporte", es: "Quattroporte" } },
      { id: "spyder", label: { en: "Spyder", es: "Spyder" } },
    ],
  },
  {
    id: "mazda",
    name: { en: "Mazda", es: "Mazda" },
    classId: "sedan",
    models: [
      { id: "bt50", label: { en: "BT-50", es: "BT-50" } },
      { id: "cx30", label: { en: "CX-30", es: "CX-30" } },
      { id: "cx5", label: { en: "CX-5", es: "CX-5" } },
      { id: "cx50", label: { en: "CX-50", es: "CX-50" } },
      { id: "cx7", label: { en: "CX-7", es: "CX-7" } },
      { id: "cx9", label: { en: "CX-9", es: "CX-9" } },
      { id: "cx90", label: { en: "CX-90", es: "CX-90" } },
      { id: "mazda2", label: { en: "Mazda2", es: "Mazda2" } },
      { id: "mazda3", label: { en: "Mazda3", es: "Mazda3" } },
      { id: "mazda5", label: { en: "Mazda5", es: "Mazda5" } },
      { id: "mazda6", label: { en: "Mazda6", es: "Mazda6" } },
      { id: "miata", label: { en: "MX-5 Miata", es: "MX-5 Miata" } },
      { id: "protege", label: { en: "Protegé", es: "Protegé" } },
      { id: "rx8", label: { en: "RX-8", es: "RX-8" } },
      { id: "tribute", label: { en: "Tribute", es: "Tribute" } },
    ],
  },
  {
    id: "mclaren",
    name: { en: "McLaren", es: "McLaren" },
    classId: "luxury_perf",
    models: [
      { id: "570s", label: { en: "570S", es: "570S" } },
      { id: "600lt", label: { en: "600LT", es: "600LT" } },
      { id: "720s", label: { en: "720S", es: "720S" } },
      { id: "765lt", label: { en: "765LT", es: "765LT" } },
      { id: "artura", label: { en: "Artura", es: "Artura" } },
      { id: "gt", label: { en: "GT", es: "GT" } },
      { id: "mp412c", label: { en: "MP4-12C", es: "MP4-12C" } },
      { id: "p1", label: { en: "P1", es: "P1" } },
      { id: "senna", label: { en: "Senna", es: "Senna" } },
    ],
  },
  {
    id: "mercedesbenz",
    name: { en: "Mercedes-Benz", es: "Mercedes-Benz" },
    classId: "luxury_perf",
    models: [
      { id: "aclass", label: { en: "A-Class", es: "Clase A" } },
      { id: "amggt", label: { en: "AMG GT", es: "AMG GT" } },
      { id: "cclass", label: { en: "C-Class", es: "Clase C" } },
      { id: "clclass", label: { en: "CL-Class", es: "Clase CL" } },
      { id: "cla", label: { en: "CLA", es: "CLA" } },
      { id: "cls", label: { en: "CLS", es: "CLS" } },
      { id: "eclass", label: { en: "E-Class", es: "Clase E" } },
      { id: "eqc", label: { en: "EQC", es: "EQC" } },
      { id: "eqe", label: { en: "EQE", es: "EQE" } },
      { id: "eqs", label: { en: "EQS", es: "EQS" } },
      { id: "eqssuv", label: { en: "EQS SUV", es: "EQS SUV" } },
      { id: "gclass", label: { en: "G-Class", es: "Clase G" } },
      { id: "glclass", label: { en: "GL-Class", es: "Clase GL" } },
      { id: "gla", label: { en: "GLA", es: "GLA" } },
      { id: "glb", label: { en: "GLB", es: "GLB" } },
      { id: "gle", label: { en: "GLE", es: "GLE" } },
      { id: "glk", label: { en: "GLK", es: "GLK" } },
      { id: "mlclass", label: { en: "M-Class", es: "Clase M" } },
      { id: "rclass", label: { en: "R-Class", es: "Clase R" } },
      { id: "sclass", label: { en: "S-Class", es: "Clase S" } },
      { id: "sl", label: { en: "SL", es: "SL" } },
      { id: "slk", label: { en: "SLK", es: "SLK" } },
      { id: "sls", label: { en: "SLS AMG", es: "SLS AMG" } },
      { id: "sprinter", label: { en: "Sprinter", es: "Sprinter" } },
    ],
  },
  {
    id: "mini",
    name: { en: "MINI", es: "MINI" },
    classId: "compact",
    models: [
      { id: "clubman", label: { en: "Clubman", es: "Clubman" } },
      { id: "convertible", label: { en: "Convertible", es: "Convertible" } },
      { id: "countryman", label: { en: "Countryman", es: "Countryman" } },
      { id: "coupe", label: { en: "Coupé", es: "Coupé" } },
      { id: "hardtop", label: { en: "Hardtop", es: "Hardtop" } },
      { id: "paceman", label: { en: "Paceman", es: "Paceman" } },
      { id: "roadster", label: { en: "Roadster", es: "Roadster" } },
    ],
  },
  {
    id: "mitsubishi",
    name: { en: "Mitsubishi", es: "Mitsubishi" },
    classId: "sedan",
    models: [
      { id: "eclipse", label: { en: "Eclipse", es: "Eclipse" } },
      { id: "eclipsecross", label: { en: "Eclipse Cross", es: "Eclipse Cross" } },
      { id: "endurance", label: { en: "Endeavor", es: "Endeavor" } },
      { id: "galant", label: { en: "Galant", es: "Galant" } },
      { id: "lancer", label: { en: "Lancer", es: "Lancer" } },
      { id: "mirage", label: { en: "Mirage", es: "Mirage" } },
      { id: "montero", label: { en: "Montero", es: "Montero" } },
      { id: "outlander", label: { en: "Outlander", es: "Outlander" } },
      { id: "outlandersport", label: { en: "Outlander Sport", es: "Outlander Sport" } },
    ],
  },
  {
    id: "nissan",
    name: { en: "Nissan", es: "Nissan" },
    classId: "sedan",
    models: [
      { id: "altima", label: { en: "Altima", es: "Altima" } },
      { id: "armada", label: { en: "Armada", es: "Armada" } },
      { id: "cube", label: { en: "Cube", es: "Cube" } },
      { id: "frontier", label: { en: "Frontier", es: "Frontier" } },
      { id: "gt", label: { en: "GT-R", es: "GT-R" } },
      { id: "juke", label: { en: "Juke", es: "Juke" } },
      { id: "kicks", label: { en: "Kicks", es: "Kicks" } },
      { id: "leaf", label: { en: "Leaf", es: "Leaf" } },
      { id: "maxima", label: { en: "Maxima", es: "Maxima" } },
      { id: "murano", label: { en: "Murano", es: "Murano" } },
      { id: "nv", label: { en: "NV", es: "NV" } },
      { id: "nv200", label: { en: "NV200", es: "NV200" } },
      { id: "pathfinder", label: { en: "Pathfinder", es: "Pathfinder" } },
      { id: "quest", label: { en: "Quest", es: "Quest" } },
      { id: "rogue", label: { en: "Rogue", es: "Rogue" } },
      { id: "sentra", label: { en: "Sentra", es: "Sentra" } },
      { id: "titan", label: { en: "Titan", es: "Titan" } },
      { id: "versa", label: { en: "Versa", es: "Versa" } },
      { id: "xterra", label: { en: "Xterra", es: "Xterra" } },
      { id: "z", label: { en: "Z", es: "Z" } },
      { id: "350z", label: { en: "350Z", es: "350Z" } },
      { id: "370z", label: { en: "370Z", es: "370Z" } },
    ],
  },
  {
    id: "polestar",
    name: { en: "Polestar", es: "Polestar" },
    classId: "luxury_perf",
    models: [
      { id: "1", label: { en: "1", es: "1" } },
      { id: "2", label: { en: "2", es: "2" } },
      { id: "3", label: { en: "3", es: "3" } },
      { id: "4", label: { en: "4", es: "4" } },
    ],
  },
  {
    id: "porsche",
    name: { en: "Porsche", es: "Porsche" },
    classId: "luxury_perf",
    models: [
      { id: "718boxster", label: { en: "718 Boxster", es: "718 Boxster" } },
      { id: "718cayman", label: { en: "718 Cayman", es: "718 Cayman" } },
      { id: "911", label: { en: "911", es: "911" } },
      { id: "944", label: { en: "944", es: "944" } },
      { id: "boxster", label: { en: "Boxster", es: "Boxster" } },
      { id: "cayenne", label: { en: "Cayenne", es: "Cayenne" } },
      { id: "cayman", label: { en: "Cayman", es: "Cayman" } },
      { id: "macan", label: { en: "Macan", es: "Macan" } },
      { id: "panamera", label: { en: "Panamera", es: "Panamera" } },
      { id: "taycan", label: { en: "Taycan", es: "Taycan" } },
    ],
  },
  {
    id: "ram",
    name: { en: "Ram", es: "Ram" },
    classId: "suv_truck",
    models: [
      { id: "1500", label: { en: "1500", es: "1500" } },
      { id: "2500", label: { en: "2500", es: "2500" } },
      { id: "3500", label: { en: "3500", es: "3500" } },
      { id: "4500", label: { en: "4500", es: "4500" } },
      { id: "5500", label: { en: "5500", es: "5500" } },
      { id: "promaster", label: { en: "ProMaster", es: "ProMaster" } },
      { id: "promastercity", label: { en: "ProMaster City", es: "ProMaster City" } },
    ],
  },
  {
    id: "rivian",
    name: { en: "Rivian", es: "Rivian" },
    classId: "suv_truck",
    models: [
      { id: "r1s", label: { en: "R1S", es: "R1S" } },
      { id: "r1t", label: { en: "R1T", es: "R1T" } },
    ],
  },
  {
    id: "rollsroyce",
    name: { en: "Rolls-Royce", es: "Rolls-Royce" },
    classId: "luxury_perf",
    models: [
      { id: "cullinan", label: { en: "Cullinan", es: "Cullinan" } },
      { id: "dawn", label: { en: "Dawn", es: "Dawn" } },
      { id: "ghost", label: { en: "Ghost", es: "Ghost" } },
      { id: "phantom", label: { en: "Phantom", es: "Phantom" } },
      { id: "spect", label: { en: "Spectre", es: "Spectre" } },
      { id: "wraith", label: { en: "Wraith", es: "Wraith" } },
    ],
  },
  {
    id: "saab",
    name: { en: "Saab", es: "Saab" },
    classId: "sedan",
    models: [
      { id: "93", label: { en: "9-3", es: "9-3" } },
      { id: "95", label: { en: "9-5", es: "9-5" } },
    ],
  },
  {
    id: "saturn",
    name: { en: "Saturn", es: "Saturn" },
    classId: "sedan",
    models: [
      { id: "aura", label: { en: "Aura", es: "Aura" } },
      { id: "ion", label: { en: "ION", es: "ION" } },
      { id: "l200", label: { en: "L-Series", es: "L-Series" } },
      { id: "outlook", label: { en: "Outlook", es: "Outlook" } },
      { id: "relay", label: { en: "Relay", es: "Relay" } },
      { id: "sky", label: { en: "Sky", es: "Sky" } },
      { id: "sline", label: { en: "S-Series", es: "S-Series" } },
      { id: "vue", label: { en: "VUE", es: "VUE" } },
    ],
  },
  {
    id: "scion",
    name: { en: "Scion", es: "Scion" },
    classId: "compact",
    models: [
      { id: "fr", label: { en: "FR-S", es: "FR-S" } },
      { id: "ia", label: { en: "iA", es: "iA" } },
      { id: "ib", label: { en: "iM", es: "iM" } },
      { id: "iq", label: { en: "iQ", es: "iQ" } },
      { id: "tc", label: { en: "tC", es: "tC" } },
      { id: "xa", label: { en: "xA", es: "xA" } },
      { id: "xb", label: { en: "xB", es: "xB" } },
      { id: "xd", label: { en: "xD", es: "xD" } },
    ],
  },
  {
    id: "smart",
    name: { en: "Smart", es: "Smart" },
    classId: "compact",
    models: [
      { id: "eqfortwo", label: { en: "EQ ForTwo", es: "EQ ForTwo" } },
      { id: "fortwo", label: { en: "ForTwo", es: "ForTwo" } },
    ],
  },
  {
    id: "subaru",
    name: { en: "Subaru", es: "Subaru" },
    classId: "sedan",
    models: [
      { id: "ascent", label: { en: "Ascent", es: "Ascent" } },
      { id: "baja", label: { en: "Baja", es: "Baja" } },
      { id: "brz", label: { en: "BRZ", es: "BRZ" } },
      { id: "crosstrek", label: { en: "Crosstrek", es: "Crosstrek" } },
      { id: "forester", label: { en: "Forester", es: "Forester" } },
      { id: "impreza", label: { en: "Impreza", es: "Impreza" } },
      { id: "legacy", label: { en: "Legacy", es: "Legacy" } },
      { id: "outback", label: { en: "Outback", es: "Outback" } },
      { id: "solterra", label: { en: "Solterra", es: "Solterra" } },
      { id: "tribeca", label: { en: "Tribeca", es: "Tribeca" } },
      { id: "wrx", label: { en: "WRX", es: "WRX" } },
      { id: "xv", label: { en: "XV", es: "XV" } },
    ],
  },
  {
    id: "suzuki",
    name: { en: "Suzuki", es: "Suzuki" },
    classId: "compact",
    models: [
      { id: "aerio", label: { en: "Aerio", es: "Aerio" } },
      { id: "equator", label: { en: "Equator", es: "Equator" } },
      { id: "grandvitara", label: { en: "Grand Vitara", es: "Grand Vitara" } },
      { id: "kizashi", label: { en: "Kizashi", es: "Kizashi" } },
      { id: "sx4", label: { en: "SX4", es: "SX4" } },
      { id: "swift", label: { en: "Swift", es: "Swift" } },
      { id: "vitara", label: { en: "Vitara", es: "Vitara" } },
    ],
  },
  {
    id: "tesla",
    name: { en: "Tesla", es: "Tesla" },
    classId: "luxury_perf",
    models: [
      { id: "cybertruck", label: { en: "Cybertruck", es: "Cybertruck" } },
      { id: "model3", label: { en: "Model 3", es: "Model 3" } },
      { id: "models", label: { en: "Model S", es: "Model S" } },
      { id: "modelx", label: { en: "Model X", es: "Model X" } },
      { id: "modely", label: { en: "Model Y", es: "Model Y" } },
      { id: "roadster", label: { en: "Roadster", es: "Roadster" } },
    ],
  },
  {
    id: "toyota",
    name: { en: "Toyota", es: "Toyota" },
    classId: "sedan",
    models: [
      { id: "4runner", label: { en: "4Runner", es: "4Runner" } },
      { id: "avalon", label: { en: "Avalon", es: "Avalon" } },
      { id: "camry", label: { en: "Camry", es: "Camry" } },
      { id: "celica", label: { en: "Celica", es: "Celica" } },
      { id: "corolla", label: { en: "Corolla", es: "Corolla" } },
      { id: "cressida", label: { en: "Cressida", es: "Cressida" } },
      { id: "crown", label: { en: "Crown", es: "Crown" } },
      { id: "fjcruiser", label: { en: "FJ Cruiser", es: "FJ Cruiser" } },
      { id: "grandhighlander", label: { en: "Grand Highlander", es: "Grand Highlander" } },
      { id: "highlander", label: { en: "Highlander", es: "Highlander" } },
      { id: "hilux", label: { en: "Hilux", es: "Hilux" } },
      { id: "landcruiser", label: { en: "Land Cruiser", es: "Land Cruiser" } },
      { id: "matrix", label: { en: "Matrix", es: "Matrix" } },
      { id: "mirai", label: { en: "Mirai", es: "Mirai" } },
      { id: "mr2", label: { en: "MR2", es: "MR2" } },
      { id: "prius", label: { en: "Prius", es: "Prius" } },
      { id: "rav4", label: { en: "RAV4", es: "RAV4" } },
      { id: "seguoia", label: { en: "Sequoia", es: "Sequoia" } },
      { id: "sienna", label: { en: "Sienna", es: "Sienna" } },
      { id: "solara", label: { en: "Solara", es: "Solara" } },
      { id: "supra", label: { en: "Supra", es: "Supra" } },
      { id: "tacoma", label: { en: "Tacoma", es: "Tacoma" } },
      { id: "tundra", label: { en: "Tundra", es: "Tundra" } },
      { id: "venza", label: { en: "Venza", es: "Venza" } },
      { id: "yaris", label: { en: "Yaris", es: "Yaris" } },
    ],
  },
  {
    id: "volkswagen",
    name: { en: "Volkswagen", es: "Volkswagen" },
    classId: "sedan",
    models: [
      { id: "atlas", label: { en: "Atlas", es: "Atlas" } },
      { id: "beetle", label: { en: "Beetle", es: "Beetle" } },
      { id: "cc", label: { en: "CC", es: "CC" } },
      { id: "eos", label: { en: "Eos", es: "Eos" } },
      { id: "golf", label: { en: "Golf", es: "Golf" } },
      { id: "golfgti", label: { en: "Golf GTI", es: "Golf GTI" } },
      { id: "golfr", label: { en: "Golf R", es: "Golf R" } },
      { id: "id4", label: { en: "ID.4", es: "ID.4" } },
      { id: "jetta", label: { en: "Jetta", es: "Jetta" } },
      { id: "passat", label: { en: "Passat", es: "Passat" } },
      { id: "phaeton", label: { en: "Phaeton", es: "Phaeton" } },
      { id: "rabbit", label: { en: "Rabbit", es: "Rabbit" } },
      { id: "roush", label: { en: "Routan", es: "Routan" } },
      { id: "tiguan", label: { en: "Tiguan", es: "Tiguan" } },
      { id: "touareg", label: { en: "Touareg", es: "Touareg" } },
    ],
  },
  {
    id: "volvo",
    name: { en: "Volvo", es: "Volvo" },
    classId: "luxury_perf",
    models: [
      { id: "c30", label: { en: "C30", es: "C30" } },
      { id: "c40", label: { en: "C40 Recharge", es: "C40 Recharge" } },
      { id: "c70", label: { en: "C70", es: "C70" } },
      { id: "ex30", label: { en: "EX30", es: "EX30" } },
      { id: "ex90", label: { en: "EX90", es: "EX90" } },
      { id: "s40", label: { en: "S40", es: "S40" } },
      { id: "s60", label: { en: "S60", es: "S60" } },
      { id: "s80", label: { en: "S80", es: "S80" } },
      { id: "s90", label: { en: "S90", es: "S90" } },
      { id: "v40", label: { en: "V40", es: "V40" } },
      { id: "v50", label: { en: "V50", es: "V50" } },
      { id: "v60", label: { en: "V60", es: "V60" } },
      { id: "v70", label: { en: "V70", es: "V70" } },
      { id: "v90", label: { en: "V90", es: "V90" } },
      { id: "xc40", label: { en: "XC40", es: "XC40" } },
      { id: "xc60", label: { en: "XC60", es: "XC60" } },
      { id: "xc70", label: { en: "XC70", es: "XC70" } },
      { id: "xc90", label: { en: "XC90", es: "XC90" } },
    ],
  },
];
