-- Quote chatbot booking schema for iammotors.
-- Run this once in the Supabase SQL editor. Every statement is safe to rerun.
-- Leads and appointments live in normalized rows so unrelated customer sessions
-- cannot overwrite one another. Reservation and slot blocking go through
-- SECURITY DEFINER functions that hold a per-day advisory lock, closing the
-- race between the availability check and the unique active-slot write.

create extension if not exists pgcrypto;

-- A customer's quote-chat lead: contact + vehicle + service + dropped-in photos.
create table if not exists public.chat_leads (
  id                    text primary key,
  session_id            text not null unique,
  source                text not null default 'Quote chat',
  lang                  text not null default 'en' check (lang in ('en', 'es')),
  status                text not null default 'new'
                        check (status in ('new', 'contacted', 'booked', 'done', 'lost')),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  appointment_requested boolean not null default false,
  summary               text not null default '',
  customer_name         text not null default '',
  phone                 text not null default '',
  vehicle               text not null default '',
  service               text not null default '',
  photos                jsonb not null default '[]'::jsonb
                        check (jsonb_typeof(photos) = 'array'),
  preferred_date        date,
  preferred_time        time(0) without time zone,
  preferred_time_text   text not null default '',
  last_message          text not null default ''
);

create table if not exists public.chat_appointments (
  id                   text primary key,
  lead_id              text references public.chat_leads(id) on delete cascade,
  session_id           text not null unique,
  status               text not null default 'requested'
                       check (status in ('requested', 'confirmed', 'completed', 'no-show', 'canceled')),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  customer_name        text not null default '',
  phone                text not null default '',
  service              text not null default '',
  vehicle              text not null default '',
  preferred_date       date,
  preferred_time       time(0) without time zone,
  preferred_time_text  text not null default '',
  notes                text not null default '',
  scheduled_date       date,
  scheduled_time       time(0) without time zone,
  constraint chat_appointments_schedule_pair check (
    (scheduled_date is null and scheduled_time is null) or
    (scheduled_date is not null and scheduled_time is not null)
  )
);

create table if not exists public.chat_blocked_slots (
  id          bigint generated by default as identity primary key,
  slot_date   date not null,
  slot_time   time(0) without time zone,
  is_all_day  boolean not null default false,
  created_at  timestamptz not null default now(),
  constraint chat_blocked_slots_shape check (
    (is_all_day and slot_time is null) or
    (not is_all_day and slot_time is not null)
  )
);

create table if not exists public.chat_rate_limits (
  rate_key           text primary key,
  window_started_at  timestamptz not null,
  request_count      integer not null default 0 check (request_count >= 0),
  expires_at         timestamptz not null,
  updated_at         timestamptz not null default now()
);

create index if not exists chat_leads_updated_idx on public.chat_leads (updated_at desc);
create index if not exists chat_appointments_updated_idx on public.chat_appointments (updated_at desc);
create index if not exists chat_appointments_lead_idx on public.chat_appointments (lead_id);
create index if not exists chat_rate_limits_expires_idx on public.chat_rate_limits (expires_at);

create unique index if not exists chat_blocked_slots_day_unique
  on public.chat_blocked_slots (slot_date) where is_all_day;
create unique index if not exists chat_blocked_slots_time_unique
  on public.chat_blocked_slots (slot_date, slot_time) where not is_all_day;

-- Only one active (requested/confirmed) appointment may hold a given slot.
create unique index if not exists chat_appointments_active_slot_unique
  on public.chat_appointments (scheduled_date, scheduled_time)
  where scheduled_date is not null
    and scheduled_time is not null
    and status in ('requested', 'confirmed');

-- Reserve a slot for the session's lead. Business hours below mirror SITE.hours
-- (Mon–Fri 09:00–18:00, Sat 09:00–17:00, Sun closed) in America/Los_Angeles.
create or replace function public.reserve_chat_appointment(
  p_identifier text,
  p_scheduled_date date,
  p_scheduled_time time without time zone
)
returns setof public.chat_appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lead public.chat_leads%rowtype;
  v_appointment public.chat_appointments%rowtype;
  v_local_now timestamp without time zone := timezone('America/Los_Angeles', now());
  v_day integer;
begin
  if coalesce(btrim(p_identifier), '') = '' then
    raise exception 'CHAT_RESERVATION_IDENTIFIER_REQUIRED' using errcode = 'P0001';
  end if;
  if p_scheduled_date is null or p_scheduled_time is null then
    raise exception 'CHAT_RESERVATION_DATE_TIME_REQUIRED' using errcode = 'P0001';
  end if;
  if extract(minute from p_scheduled_time) <> 0 or extract(second from p_scheduled_time) <> 0 then
    raise exception 'CHAT_RESERVATION_INVALID_INTERVAL' using errcode = 'P0001';
  end if;
  if p_scheduled_date < v_local_now::date or
     (p_scheduled_date = v_local_now::date and p_scheduled_time <= v_local_now::time) then
    raise exception 'CHAT_RESERVATION_PAST' using errcode = 'P0001';
  end if;

  v_day := extract(dow from p_scheduled_date);
  if v_day = 0 or
     (v_day between 1 and 5 and (p_scheduled_time < time '09:00' or p_scheduled_time >= time '18:00')) or
     (v_day = 6 and (p_scheduled_time < time '09:00' or p_scheduled_time >= time '17:00')) then
    raise exception 'CHAT_RESERVATION_OUTSIDE_BUSINESS_HOURS' using errcode = 'P0001';
  end if;

  select l.* into v_lead
  from public.chat_leads l
  where l.id = p_identifier or l.session_id = p_identifier
  order by case when l.id = p_identifier then 0 else 1 end
  limit 1;

  if not found then
    select l.* into v_lead
    from public.chat_appointments a
    join public.chat_leads l on l.id = a.lead_id or l.session_id = a.session_id
    where a.id = p_identifier or a.session_id = p_identifier
    order by case when a.id = p_identifier then 0 else 1 end
    limit 1;
  end if;

  if v_lead.id is null then
    raise exception 'CHAT_RESERVATION_LEAD_NOT_FOUND' using errcode = 'P0001';
  end if;
  if btrim(v_lead.service) = '' or btrim(v_lead.vehicle) = '' or
     btrim(v_lead.customer_name) = '' or btrim(v_lead.phone) = '' then
    raise exception 'CHAT_RESERVATION_DETAILS_REQUIRED' using errcode = 'P0001';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('chat-date:' || p_scheduled_date::text, 0));

  if exists (
    select 1 from public.chat_blocked_slots b
    where b.slot_date = p_scheduled_date
      and (b.is_all_day or b.slot_time = p_scheduled_time)
  ) then
    raise exception 'CHAT_RESERVATION_BLOCKED' using errcode = 'P0001';
  end if;

  select a.* into v_appointment
  from public.chat_appointments a
  where a.id = p_identifier
     or a.session_id = p_identifier
     or a.session_id = v_lead.session_id
  order by case when a.id = p_identifier then 0 else 1 end
  limit 1
  for update;

  if v_appointment.id is null then
    insert into public.chat_appointments (
      id, lead_id, session_id, status, customer_name, phone, service, vehicle,
      preferred_date, preferred_time, preferred_time_text, notes
    ) values (
      'appt_' || replace(gen_random_uuid()::text, '-', ''),
      v_lead.id,
      v_lead.session_id,
      'requested',
      v_lead.customer_name,
      v_lead.phone,
      v_lead.service,
      v_lead.vehicle,
      v_lead.preferred_date,
      v_lead.preferred_time,
      v_lead.preferred_time_text,
      v_lead.summary
    )
    returning * into v_appointment;
  end if;

  if exists (
    select 1 from public.chat_appointments a
    where a.id <> v_appointment.id
      and a.scheduled_date = p_scheduled_date
      and a.scheduled_time = p_scheduled_time
      and a.status in ('requested', 'confirmed')
  ) then
    raise exception 'CHAT_RESERVATION_CONFLICT' using errcode = 'P0001';
  end if;

  begin
    update public.chat_appointments
    set scheduled_date = p_scheduled_date,
        scheduled_time = p_scheduled_time,
        status = 'confirmed',
        customer_name = v_lead.customer_name,
        phone = v_lead.phone,
        service = v_lead.service,
        vehicle = v_lead.vehicle,
        preferred_date = coalesce(v_lead.preferred_date, p_scheduled_date),
        preferred_time = coalesce(v_lead.preferred_time, p_scheduled_time),
        preferred_time_text = v_lead.preferred_time_text,
        notes = v_lead.summary,
        updated_at = now()
    where id = v_appointment.id
    returning * into v_appointment;
  exception when unique_violation then
    raise exception 'CHAT_RESERVATION_CONFLICT' using errcode = 'P0001';
  end;

  return next v_appointment;
end;
$$;

create or replace function public.block_chat_slot(
  p_slot_date date,
  p_slot_time time without time zone,
  p_all_day boolean default false
)
returns table(action text)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_slot_date is null or
     (coalesce(p_all_day, false) and p_slot_time is not null) or
     (not coalesce(p_all_day, false) and p_slot_time is null) then
    raise exception 'CHAT_BLOCK_INVALID' using errcode = 'P0001';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('chat-date:' || p_slot_date::text, 0));

  if exists (
    select 1 from public.chat_appointments a
    where a.scheduled_date = p_slot_date
      and (p_all_day or a.scheduled_time = p_slot_time)
      and a.status in ('requested', 'confirmed')
  ) then
    raise exception 'CHAT_BLOCK_RESERVED_SLOT' using errcode = 'P0001';
  end if;

  if exists (
    select 1 from public.chat_blocked_slots b
    where b.slot_date = p_slot_date
      and (b.is_all_day or (not p_all_day and b.slot_time = p_slot_time))
  ) then
    action := 'already_blocked';
    return next;
    return;
  end if;

  if p_all_day then
    delete from public.chat_blocked_slots
    where slot_date = p_slot_date and not is_all_day;
  end if;

  insert into public.chat_blocked_slots (slot_date, slot_time, is_all_day)
  values (p_slot_date, case when p_all_day then null else p_slot_time end, p_all_day)
  on conflict do nothing;

  action := 'blocked';
  return next;
end;
$$;

create or replace function public.consume_chat_rate_limit(
  p_key text,
  p_limit integer,
  p_window_seconds integer
)
returns table(allowed boolean, remaining integer, reset_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_limit integer := greatest(1, least(coalesce(p_limit, 1), 100000));
  v_window integer := greatest(1, least(coalesce(p_window_seconds, 60), 86400));
  v_count integer;
  v_expires timestamptz;
begin
  if coalesce(btrim(p_key), '') = '' then
    raise exception 'CHAT_RATE_LIMIT_KEY_REQUIRED' using errcode = 'P0001';
  end if;

  insert into public.chat_rate_limits (
    rate_key, window_started_at, request_count, expires_at, updated_at
  ) values (
    left(p_key, 200), v_now, 1, v_now + make_interval(secs => v_window), v_now
  )
  on conflict (rate_key) do update
  set window_started_at = case
        when public.chat_rate_limits.expires_at <= v_now then v_now
        else public.chat_rate_limits.window_started_at end,
      request_count = case
        when public.chat_rate_limits.expires_at <= v_now then 1
        else public.chat_rate_limits.request_count + 1 end,
      expires_at = case
        when public.chat_rate_limits.expires_at <= v_now then v_now + make_interval(secs => v_window)
        else public.chat_rate_limits.expires_at end,
      updated_at = v_now
  returning request_count, expires_at into v_count, v_expires;

  allowed := v_count <= v_limit;
  remaining := greatest(0, v_limit - v_count);
  reset_at := v_expires;
  return next;
end;
$$;

-- Server code uses the service role only; no anon/authenticated access.
alter table public.chat_leads enable row level security;
alter table public.chat_appointments enable row level security;
alter table public.chat_blocked_slots enable row level security;
alter table public.chat_rate_limits enable row level security;

revoke all on public.chat_leads from anon, authenticated;
revoke all on public.chat_appointments from anon, authenticated;
revoke all on public.chat_blocked_slots from anon, authenticated;
revoke all on public.chat_rate_limits from anon, authenticated;

revoke execute on function public.reserve_chat_appointment(text, date, time without time zone) from public, anon, authenticated;
revoke execute on function public.block_chat_slot(date, time without time zone, boolean) from public, anon, authenticated;
revoke execute on function public.consume_chat_rate_limit(text, integer, integer) from public, anon, authenticated;

grant execute on function public.reserve_chat_appointment(text, date, time without time zone) to service_role;
grant execute on function public.block_chat_slot(date, time without time zone, boolean) to service_role;
grant execute on function public.consume_chat_rate_limit(text, integer, integer) to service_role;
